### ISSUE TITLE
Font size

### ISSUE THREAD

**Issue by pagenstedt** [diamondburned/dissent#150]
On my screen fonts are quite small. 
Would be great to have option for changing font size or scaling

**Comment by rubiojr** [comment]
Stolen from https://github.com/diamondburned/dissent/issues/135, this worked for me:

```css
.window-chatpage {
  font-size: 22px;
}

.message-content-box {
  padding: 20px;
}

.message-content-box .message-reply-content {
  font-size: 22px;
}

.message-normalembed .message-normalembed-body {
  font-size: 22px;
}
```

Save it to `$HOME/.config/dissent/user.css` or `$HOME/.var/app/so.libdb.dissent/config` when using Flatpak.

Got the CSS classes from [message.go](https://github.com/diamondburned/dissent/blob/f1db845f6dd715bae3b8251c3d91b572a538eb55/internal/messages/message.go), [chat.go](https://github.com/diamondburned/dissent/blob/f1db845f6dd715bae3b8251c3d91b572a538eb55/internal/window/chat.go)  and [content.go](https://github.com/diamondburned/dissent/blob/f1db845f6dd715bae3b8251c3d91b572a538eb55/internal/messages/content.go).
