### ISSUE TITLE
Design tweaks wishlist

### ISSUE THREAD

**Issue by diamondburned** [diamondburned/dissent#266]
This issue serves as a place to consolidate very small design changes that would massively improve the appearance of Dissent.

**Comment by diamondburned** [comment]
Fix inconsistent sidebar colors.

Dissent:

![image](https://github.com/diamondburned/dissent/assets/8463786/e7929ad8-8420-4872-a4d5-da323dba91e3)

Tuba:

![image](https://github.com/diamondburned/dissent/assets/8463786/4906b9c9-81c4-4ceb-a288-f26644c0f20b)

**Comment by diamondburned** [comment]
Switch to margin-separated rounded corner message theming for a more modern look. Current appearance:

![image](https://github.com/diamondburned/dissent/assets/8463786/284a23c1-06d2-417a-b039-b4af52bfcb67)

**Comment by diamondburned** [comment]
Prettier loading screen. Ideally, have a logo in the middle with no text.

Tuba:

![image](https://github.com/diamondburned/dissent/assets/8463786/9c2fff6f-b8fc-4b86-a74f-a28826440fa5)

**Comment by diamondburned** [comment]
Fix inconsistent title margins:

![image](https://github.com/diamondburned/dissent/assets/8463786/c4398dc0-df97-4994-a4bf-b08dc532955a)

**Comment by diamondburned** [comment]
Fix incorrect colors when selecting a muted channel. Current:

![image](https://github.com/diamondburned/dissent/assets/8463786/5596edb6-76ec-4ac0-8eac-b7f6f7f699b9)

**Comment by diamondburned** [comment]
Server icon should remain a roundrect when selected instead of going back to a circle:

![image](https://github.com/diamondburned/dissent/assets/8463786/d6eb51b0-fc8e-44c8-9120-dc6abe0dc2fa)

**Comment by bragefuglseth** [comment]
> Prettier loading screen. Ideally, have a logo in the middle with no text.
> 
> Tuba:
> 
> ![image](https://private-user-images.githubusercontent.com/8463786/318990967-9c2fff6f-b8fc-4b86-a74f-a28826440fa5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0NDU0ODMsIm5iZiI6MTcxMjQ0NTE4MywicGF0aCI6Ii84NDYzNzg2LzMxODk5MDk2Ny05YzJmZmY2Zi1iOGZjLTRiODYtYTc0Zi1hMjg4MjY0NDBmYTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDZUMjMxMzAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Zjg0NTA0YWJkNThmYjIwNTY3ODg2ZTIyOTkwMTA5MzViZTE4NTZkNzc1NDAyZDQ2YzE3NWMxOWM2MzJlZWUyNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.YGE5keO69J9MU-Doa90DWxoO_tE-O2OoI9YssZHVN4c)

FWIW Tuba has moved away from this, and now only shows a spinner

**Comment by DodoLeDev** [comment]
Hi everyone!
I spent some time playing with the `user.css` feature hidden in Dissent.

### Here are my design suggestions, and the corresponding CSS blocks to be added in the file if you want to try it :

#### Redesigned unread indicators :red_circle: 
For this one, I took a part of my inspiration from Fractal…
![Fractal screenshot](https://github.com/diamondburned/dissent/assets/59477313/fc646d7d-a5cd-4fa7-850f-845a9d518f1b)

Here is how it looks on Dissent:
![Dissent custom unread indicators](https://github.com/diamondburned/dissent/assets/59477313/3bb62a3e-3e30-438f-89c4-6a36d6cee17d)

<details>
<summary>CSS code</summary>

```css
.channel-item-outer {
  padding: 2px;
  border-radius: 5px;
  margin: 3px;
}

.channel-item-unread, .channel-item-mentioned {
  font-weight: 800;
}

.channel-item-unread .channel-item-text > overlay {
  background-color: #454545;
}

.channel-item-mentioned .channel-item-text > overlay {
  background-color: #f04747;
}

.channel-item-text > overlay {
  border-radius: 99px;
  margin-right: 7px;
}

.channel-item-unread .channel-unread-indicator, .channel-item-mentioned .channel-unread-indicator {
  min-width: 0px;
  opacity: 0;
}
```
</details>

---

#### Fractal-like composer action button :pencil2: 
Still inspired by Fractal, introducing a more seducing send/edit/reply button:
![image](https://github.com/diamondburned/dissent/assets/59477313/ef35c99e-eb82-45cd-97bd-d9e1ca6a2377) ![image](https://github.com/diamondburned/dissent/assets/59477313/452358c6-a280-422a-a4d3-23116c68136d) ![image](https://github.com/diamondburned/dissent/assets/59477313/e3991c11-5ed0-4ca0-bb20-a452da39063a)

<details>
<summary>CSS code</summary>

```css
.composer-send, .composer-right-actions .composer-action {
  background-color: rgb(53, 132, 228);
  border-radius: 99px;
}

.composer-send:hover, .composer-right-actions .composer-action:hover {
  background-color: #4990e7;
}

.composer-send:focus, .composer-right-actions .composer-action:focus {
  background-color: #2a6ab6;
}
```
</details>

---

#### Clearer reply quote :speech_balloon:
I found the old design too difficult to distinguish from the real message

![image](https://github.com/diamondburned/dissent/assets/59477313/54df5a33-b868-4850-9d4c-fc4779798f5d)

<details>
<summary>CSS code</summary>

```css
.message-reply-box {
  border: none;
  padding: 5px 8px;
  background-color: rgba(255, 255, 255, 0.1);
  border-radius: 5px;
}

.message-reply-box > .mauthor-chip {
  margin-bottom: 5px;
}

.message-reply-box > .message-reply-content > link {
  text-decoration: none;
}
```
</details>

---

#### Redesigned attachments 📎
Same as reply quotes, I found the attachments not enough highlighted from the rest of the message:
![image](https://github.com/diamondburned/dissent/assets/59477313/a6eb7580-0d70-4db1-acca-f7399f28a542)

<details>
<summary>CSS code</summary>

```css
.message-attachment {
  padding: 7px 5px;
  margin-right: 10px;
  background-color: rgba(255, 255, 255, 0.1);
  border-radius: 6px;
}

.message-attachment-filesize {
  padding: 0 5px;
  margin: 5px 0 5px 10px;
  background-color: rgba(255, 255, 255, 0.2);
  border-radius: 99px;
  font-size: 12px;
}

.link.message-attachment-filename > link {
  color: #D2D7DB;
  text-decoration-line: none;
}

.message-attachment-icon {
  -gtk-icon-size: 30px;
}
```
</details>

---

#### Revamped emoji reactions :joy:
In order to keep it close from what we have in Discord (and in Fractal too :stuck_out_tongue:):
![image](https://github.com/diamondburned/dissent/assets/59477313/6cbd263f-3bfd-470c-830c-3a0c4c5af031)
![There's also a little animation!](https://github.com/diamondburned/dissent/assets/59477313/5d6bf3b5-9edf-41f2-be9b-608e70615f48)

<details>
<summary>CSS code</summary>

```css
.message-reactions .message-reaction {
  padding: 3px 10px;
  border-radius: 99px;
}

.message-reaction .horizontal {
  margin: 0;
}

.message-reaction {
  border: 1px solid transparent;
}

.message-reaction-me {
  background-color: #36567c;
  border: 1px solid #4e7bb1;
}

.message-reaction-emoji { font-size: 13px; }

.message-reaction-me {
  background-color: #36567c;
  border: 1px solid #4e7bb1;
  animation: react-trigger 0.15s alternate 2;
}

@keyframes react-trigger {
  from {transform: scale(1);}
  to {transform: scale(1.1);}
}
```
</details>

---

#### Unify sidebar color :art: 

> Fix inconsistent sidebar colors.
> 
> Dissent:
> 
> ![image](https://private-user-images.githubusercontent.com/8463786/318991505-e7929ad8-8420-4872-a4d5-da323dba91e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3MzY2MzUsIm5iZiI6MTcxODczNjMzNSwicGF0aCI6Ii84NDYzNzg2LzMxODk5MTUwNS1lNzkyOWFkOC04NDIwLTQ4NzItYTRkNS1kYTMyM2RiYTkxZTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MThUMTg0NTM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTlhYmVjMjIxZWJiYmQ2MzNhZWNmNWFlYTZlN2M5ZWFkY2UxNzdlYWU0NzAzZWMwYjZjZTRiMjY3NzdiNTliNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.yKsvK6dcUOlp1_2KgUFcrilmZlpIvMzllgNvG91eUqk)

Hmmm... I can offer some adjustements for that:
![image](https://github.com/diamondburned/dissent/assets/59477313/9b73eea7-4b1d-4e39-a206-357fb658d5d6)

<details>
<summary>CSS code</summary>

```css
.sidebar-guildside.vertical {
  background-color: transparent;
  border-right: solid rgba(255, 255, 255, 0.15) 1px;
}

.direct-searchbar.titlebar {
  background-color: transparent;
}
```
</details>

---

#### Header margins fix :straight_ruler: 

> Fix inconsistent title margins. Ideally, update this to Discord mobile's new design.
> 
> ![image](https://private-user-images.githubusercontent.com/8463786/318991855-c4398dc0-df97-4994-a4bf-b08dc532955a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3MzY2MzUsIm5iZiI6MTcxODczNjMzNSwicGF0aCI6Ii84NDYzNzg2LzMxODk5MTg1NS1jNDM5OGRjMC1kZjk3LTQ5OTQtYTRiZi1iMDhkYzUzMjk1NWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MThUMTg0NTM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDMxZTRhNTQ5Yjg0MDY4ODY3ZmU3M2U2YjE4YmQxNDIyY2Y5OGM2YzcyM2QyNGNhZWY1YjdiZTY2MzA3OGQzYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.GcqYlFh6Spaqc_2gT6LloC-KSVzMnygAOiNm5lOVJLU)

I got you covered… for the PM searchbar at least!
![image](https://github.com/diamondburned/dissent/assets/59477313/f174fd60-8a96-4f77-82f5-981977fa9641)

<details>
<summary>CSS code</summary>

```css
.search {
  padding-top: 1px;
  padding-bottom: 1px;
  margin-top: 2px;
  margin-bottom: 2px;
}
```
</details>

_Hope you'll like it!_
